version: '3.9'

services:

  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapiauth
  fastapi:
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    build: app
    ports:
      - "8000:8000"
    depends_on:
      - db